### ISSUE TITLE
Quick Look Guide for Just Conference Attendance

### ISSUE THREAD

**Issue by PiaScott** [18F/training#8]
What is the process to attend a conference?

**Comment by jackiekazil** [comment]
2 questions -- 
- What is the difference between this ticket & #9?
- The title of this ticket suggests that this is a "create" task, but the question is suggests that this is a research task. Is this is a research task or a create task? (Should this be separated into two tasks?)

**Comment by StephanieRivera** [comment]
Do we need this ticket if we have a quick look for events (including conferences), and a quick look for training (including conferences)?  I'm thinking it might be a good idea to split it up the Quick Look guides by Action (i.e. speaking, training, recruiting)  rather than venue type (ie. conference, classroom)
